[[role_flag]]
name="replay"
allocateNum=8978
payout=0
ctrl="replay"

[[role_flag]]
name="bell"
allocateNum=6827
payout=9
ctrl="bell"

[[role_flag]]
name="suika"
allocateNum=811
payout=12
ctrl="suikaA"

[[role_flag]]
name="suika"
allocateNum=510
payout=12
ctrl="suikaB"

[[role_flag]]
name="cherry"
allocateNum=2010
payout=4
ctrl="cherry"

[[bonus_flag]]
name="redBB"
allocateNum=120
payout=0
ctrl="redBB"

[[bonus_flag]]
name="blueBB"
allocateNum=120
payout=0
ctrl="blueBB"

[[bonus_flag]]
name="RB"
allocateNum=120
payout=0
ctrl="RB"


